name: Validate Migrations

on: pull_request

jobs:
  migrations:
    name: Validate migrations on staging
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"
          cache: npm

      - run: npm ci

      - run: npm run migrations:build:migrations

      - name: Run migrations on staging database
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_STAGING }}
        run: |
          npx node-pg-migrate \
            -m dist/infra/migrations \
            up
